#!/bin/bash
###############################################################################
# irace tuning script for CGP.jl
#
# PARAMETERS:
# $1 is the ID of the candidate to be evaluated
# $2 is the instance ID
# $3 is the seed
# $4 is the instance name
# The rest ($* after `shift 4') are parameters for running ACOTSP
#
# RETURN VALUE:
# This script should print a single numerical value (the value to be minimized).
###############################################################################

EXE=/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia
export JULIA_LOAD_PATH=/Users/richard/Developer/evolution/cga/forked/CGP.jl/src

CONFIG_ID="$1"
INSTANCE_ID="$2"
SEED="$3"
INSTANCE="$4"
# All other parameters are the candidate parameters to be passed to program
shift 4 || error "Not enough parameters to $0"
CONFIG_PARAMS=$*

LOG_DIR=irace_logs
mkdir -p ${LOG_DIR}
STDOUT=${LOG_DIR}/c${CONFIG_ID}-${INSTANCE_ID}.stdout
STDERR=${LOG_DIR}/c${CONFIG_ID}-${INSTANCE_ID}.stderr

error() {
    echo "`TZ=UTC date`: error: $@" >&2
    exit 1
}

# Control number of frames in each game. Set low (200?) for irace --check
MAX_FRAMES=200

# Number of evaluations to perform on a given tournament. Set low (500?) for irace --check
TOTAL_EVALS=500

LOG_FILE=${LOG_DIR}/${INSTANCE_ID}_${CONFIG_ID}.log
$EXE $INSTANCE --frames ${MAX_FRAMES} --total_evals ${TOTAL_EVALS} --seed $SEED --log ${LOG_FILE} ${CONFIG_PARAMS} 1> $STDOUT 2> $STDERR

COST=$(tail -n 2 ${LOG_FILE} | head -n 1 | cut -d 'Z' -f 2)
if ! [[ "$COST" =~ ^[-+0-9.e]+$ ]] ; then
    error "${STDOUT}: Output is not a number"
fi

echo "$COST"

# We are done with our duty. Clean files and exit with 0 (no error).
#rm -f "${STDOUT}" "${STDERR}"
#rm -f best.* stat.* cmp.*
exit 0
